SET @ESTATUnitCode=(SELECT NUTS FROM METADATA LIMIT 1);

DROP TABLE IF EXISTS POPULATION_EXPOSURE;
CREATE TABLE POPULATION_EXPOSURE(PK VARCHAR, ESTATUnitCode VARCHAR DEFAULT @ESTATUnitCode, UUEID VARCHAR, EXPOSURETYPE VARCHAR,
 NOISELEVEL VARCHAR, EXPOSEDPEOPLE INT DEFAULT(0), EXPOSEDAREA REAL DEFAULT(null), EXPOSEDDWELLINGS INT DEFAULT(0),
 EXPOSEDHOSPITALS INT DEFAULT(null), EXPOSEDSCHOOLS INT DEFAULT(null), CPI INT DEFAULT(0), HA INT DEFAULT(0), HSD INT DEFAULT(0), 
 POP_ACCURATE DOUBLE DEFAULT(0), MIN_LAEQ DOUBLE DEFAULT(0), INTERVAL_LAEQ DOUBLE DEFAULT(0), MAX_LAEQ DOUBLE DEFAULT(0));

INSERT INTO POPULATION_EXPOSURE(PK, UUEID, EXPOSURETYPE, NOISELEVEL, MIN_LAEQ, INTERVAL_LAEQ, MAX_LAEQ) SELECT CONCAT(CONCAT(UUEID, '_'), NOISELEVEL) PK,
UUEID, EXPOSURETYPE, NOISELEVEL, MIN_LAEQ, INTERVAL_LAEQ, MAX_LAEQ FROM UUEIDS_LEVELS;

DROP index if exists RECEIVERS_BUILDING_BUILD_PK;
CREATE index RECEIVERS_BUILDING_BUILD_PK on RECEIVERS_BUILDING (BUILD_PK);

DROP index if exists BUILDINGS_ERPS_ID_BAT;
CREATE index BUILDINGS_ERPS_ID_BAT on  BUILDINGS_ERPS (ID_BAT);
